### PR TITLE
Add upstream `listenToHash` function

### PR DESCRIPTION
**Pull request by joshgillies**
Ref: #3

### CODE REVIEW

**Comment by bendrucker** [comment]
Thanks Josh! Needs tests before we can merge though.

**Comment by bendrucker** [comment]
Actually I'll just take care of this now

**Comment by joshgillies** [comment]
Of course! I have some time in the coming days where I'll be able to get
onto this.

Any thoughts on how to adequately test this feature?

**Comment by bendrucker** [comment]
Already done, going up as 1.0.0 in a few mins with some breaking changes. I'm removing the ability to unlisten across the board since it's going to be hard to implement on `toHash`.

**Comment by bendrucker** [comment]
Actually may need to implement an unlisten fn for toHash first

**Comment by joshgillies** [comment]
Solid! :+1:

**Pull request closed without merging**
